application: neverendingmonologue
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /audio
  static_dir: audio

- url: /.*
  script: neverendingmonologue.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest